# frozen_string_literal: true
source 'http://rubygems.org'

ruby '2.3.1'

# this file is pretty much only used for adding migrations
gem 'rails'

gem 'central-support', path: File.expand_path("../../../..", __FILE__)

gem 'devise'
gem 'pg'
gem 'friendly_id'
gem 'foreigner'

group :test do
  gem 'test-unit'
  gem 'rspec-rails'
  gem 'rspec-its'
  gem 'rspec-activemodel-mocks'
  gem 'shoulda-matchers'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'codeclimate-test-reporter', require: nil
  gem 'timecop'
end

group :development, :test do
  gem 'awesome_print'
  gem 'pry-byebug'
  gem 'listen'
end
